<?php

namespace Database\Seeders;

use App\Models\Product;
use Illuminate\Database\Seeder;

class ProductsSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $products = [
            [
                'name' => 'Navapasanam Lord Murugan Statue',
                'slug' => 'navapasanam-lord-murugan-statue',
                'sku' => 'BOG-MUR-01',
                'category_id' => \App\Models\Category::where('slug', 'statues')->first()?->id,
                'collection' => 'Aurvi Plus Classics',
                'price' => 150000,
                'compare_price' => null,
                'stock' => 5,
                'low_stock' => 2,
                'inventory_status' => 'in_stock',
                'tax_class' => 'standard',
                'is_featured' => true,
                'is_new_arrival' => true,
                'allow_backorders' => false,
                'is_active' => true,
                'badge_text' => null,
                'rating' => 5.0,
                'reviews_count' => 128,
                'short_description' => 'A unique alchemical creation from nine poisons by Auvri Plus. Enshrined in Palani & Poombarai. (Rs. 600/gm).',
                'description' => 'A revered statue created with ancient Aurvi Plus alchemy. Crafted to channel divine energy, this Murugan statue is cherished for its spiritual potency and artisan detailing.',
                'primary_image' => 'auri-images/products/MURUGAN_STATUE.png',
                'gallery_images' => [
                    'auri-images/products/MURUGAN_STATUE.png',
                ],
                'weight' => '12',
                'dimensions' => '28 x 18 x 40',
                'material' => 'Aurvi Plus compound',
                'origin' => 'Palani Hills',
                'tags' => 'murugan, statue, temple, handcrafted',
                'meta_title' => 'Navapasanam Lord Murugan Statue - Auvri Plus',
                'meta_description' => 'A sacred Murugan statue crafted with Aurvi Plus blend for spiritual prosperity.',
            ],
            [
                'name' => 'Aurvi Plus Shivlingam',
                'slug' => 'Aurvi Plus-shivlingam',
                'sku' => 'BOG-SHV-02',
                'category_id' => \App\Models\Category::where('slug', 'statues')->first()?->id,
                'collection' => 'Aurvi Plus Classics',
                'price' => 6000,
                'compare_price' => null,
                'stock' => 12,
                'low_stock' => 3,
                'inventory_status' => 'in_stock',
                'tax_class' => 'standard',
                'is_featured' => true,
                'is_new_arrival' => true,
                'allow_backorders' => false,
                'is_active' => true,
                'badge_text' => null,
                'rating' => 5.0,
                'reviews_count' => 128,
                'short_description' => 'Highly fortunate to have in house or business. It can create wonder in life, remove planetary disturbances, and fulfill wishes.',
                'description' => 'A divine manifestation created through the ancient alchemical science of Auvri Plus. This Shivlingam represents the synthesis of cosmic energy and earthly detoxification.',
                'primary_image' => 'auri-images/products/SHIVALINGAM.png',
                'gallery_images' => [
                    'auri-images/products/SHIVALINGAM.png',
                    'auri-images/products/SHIVALINGAM_PEDESTAL.png',
                ],
                'weight' => '1.8',
                'dimensions' => '14 x 14 x 22',
                'material' => 'Aurvi Plus compound',
                'origin' => 'Palani Hills',
                'tags' => 'shivlingam, statue, sacred',
                'meta_title' => 'Aurvi Plus Shivlingam - Auvri Plus',
                'meta_description' => 'A sacred Shivlingam crafted with Aurvi Plus blend to protect your space.',
            ],
            [
                'name' => 'Navapasanam Locket',
                'slug' => 'navapasanam-locket',
                'sku' => 'BOG-BEAD-03',
                'category_id' => \App\Models\Category::where('slug', 'accessories')->first()?->id,
                'collection' => 'Aurvi Plus Essentials',
                'price' => 4500,
                'compare_price' => null,
                'stock' => 10,
                'low_stock' => 2,
                'inventory_status' => 'in_stock',
                'tax_class' => 'standard',
                'is_featured' => true,
                'is_new_arrival' => true,
                'allow_backorders' => true,
                'is_active' => true,
                'badge_text' => 'Trending',
                'rating' => 5.0,
                'reviews_count' => 84,
                'short_description' => 'A powerful spiritual healing bead created by Auvri Plus. An alchemical wonder combining nine powerful substances.',
                'description' => 'A sacred locket designed for daily spiritual protection. Crafted from Aurvi Plus blend to amplify positive energy.',
                'primary_image' => 'auri-images/products/Aurvi Plus_LOCKET.png',
                'gallery_images' => [
                    'auri-images/products/Aurvi Plus_LOCKET.png',
                ],
                'weight' => '0.04',
                'dimensions' => '2 x 2 x 0.6',
                'material' => 'Aurvi Plus compound',
                'origin' => 'Palani Hills',
                'tags' => 'bead, locket, healing',
                'meta_title' => 'Navapasanam Locket - Auvri Plus',
                'meta_description' => 'A sacred Aurvi Plus locket for daily protection and spiritual clarity.',
            ],
            [
                'name' => 'Sacred Chain',
                'slug' => 'sacred-chain',
                'sku' => 'BOG-CHAIN-04',
                'category_id' => \App\Models\Category::where('slug', 'jewelry')->first()?->id,
                'collection' => 'Aurvi Plus Essentials',
                'price' => 3500,
                'compare_price' => null,
                'stock' => 25,
                'low_stock' => 5,
                'inventory_status' => 'in_stock',
                'tax_class' => 'standard',
                'is_featured' => true,
                'is_new_arrival' => false,
                'allow_backorders' => false,
                'is_active' => true,
                'badge_text' => null,
                'rating' => 4.5,
                'reviews_count' => 62,
                'short_description' => 'Elegant and spiritual sacred chain, perfect for daily wear or pairing with your favorite Aurvi Plus locket.',
                'description' => 'A refined sacred chain designed to pair with Aurvi Plus lockets. Lightweight, durable, and crafted for spiritual comfort.',
                'primary_image' => 'auri-images/products/SACRED_CHAIN.png',
                'gallery_images' => [
                    'auri-images/products/SACRED_CHAIN.png',
                ],
                'weight' => '0.08',
                'dimensions' => '45 cm',
                'material' => 'Sacred metal alloy',
                'origin' => 'Chennai',
                'tags' => 'chain, jewelry, sacred',
                'meta_title' => 'Sacred Chain - Auvri Plus',
                'meta_description' => 'Elegant chain crafted to complement Aurvi Plus lockets.',
            ],
            [
                'name' => 'Aurvi Plus Bracelet',
                'slug' => 'Aurvi Plus-bracelet',
                'sku' => 'BOG-BRACE-05',
                'category_id' => \App\Models\Category::where('slug', 'jewelry')->first()?->id,
                'collection' => 'Aurvi Plus Essentials',
                'price' => 12000,
                'compare_price' => null,
                'stock' => 8,
                'low_stock' => 2,
                'inventory_status' => 'in_stock',
                'tax_class' => 'standard',
                'is_featured' => true,
                'is_new_arrival' => true,
                'allow_backorders' => false,
                'is_active' => true,
                'badge_text' => null,
                'rating' => 5.0,
                'reviews_count' => 46,
                'short_description' => 'A sacred jewelry piece composed of nine medicinal gems/herbs. An ancient alchemical formula for spiritual protection.',
                'description' => 'Handcrafted bracelet infused with Aurvi Plus essence. Supports balance, protection, and spiritual alignment.',
                'primary_image' => 'auri-images/products/BRACELET.png',
                'gallery_images' => [
                    'auri-images/products/BRACELET.png',
                ],
                'weight' => '0.12',
                'dimensions' => '18 cm',
                'material' => 'Aurvi Plus compound',
                'origin' => 'Palani Hills',
                'tags' => 'bracelet, jewelry, protection',
                'meta_title' => 'Aurvi Plus Bracelet - Auvri Plus',
                'meta_description' => 'Sacred bracelet crafted to amplify spiritual protection.',
            ],
            [
                'name' => 'Aurvi Plus Ring - 10gm',
                'slug' => 'Aurvi Plus-ring-10gm',
                'sku' => 'BOG-RING-06',
                'category_id' => \App\Models\Category::where('slug', 'jewelry')->first()?->id,
                'collection' => 'Aurvi Plus Essentials',
                'price' => 6000,
                'compare_price' => null,
                'stock' => 10,
                'low_stock' => 2,
                'inventory_status' => 'in_stock',
                'tax_class' => 'standard',
                'is_featured' => true,
                'is_new_arrival' => false,
                'allow_backorders' => false,
                'is_active' => true,
                'badge_text' => 'Premium',
                'rating' => 5.0,
                'reviews_count' => 52,
                'short_description' => 'Handcrafted from 9 herbs/minerals. A powerful alchemical concoction for spiritual and health benefits.',
                'description' => 'A premium ring infused with Aurvi Plus compounds, designed for balance and spiritual amplification.',
                'primary_image' => 'auri-images/products/RING.png',
                'gallery_images' => [
                    'auri-images/products/RING.png',
                ],
                'weight' => '0.01',
                'dimensions' => 'Adjustable',
                'material' => 'Aurvi Plus compound',
                'origin' => 'Palani Hills',
                'tags' => 'ring, jewelry, premium',
                'meta_title' => 'Aurvi Plus Ring - Auvri Plus',
                'meta_description' => 'Premium Aurvi Plus ring for spiritual and health benefits.',
            ],
            [
                'name' => 'Aurvi Plus Pyramid',
                'slug' => 'Aurvi Plus-pyramid',
                'sku' => 'BOG-PYR-07',
                'category_id' => \App\Models\Category::where('slug', 'spiritual')->first()?->id,
                'collection' => 'Aurvi Plus Rituals',
                'price' => 12000,
                'compare_price' => null,
                'stock' => 6,
                'low_stock' => 2,
                'inventory_status' => 'in_stock',
                'tax_class' => 'standard',
                'is_featured' => true,
                'is_new_arrival' => false,
                'allow_backorders' => false,
                'is_active' => true,
                'badge_text' => null,
                'rating' => 5.0,
                'reviews_count' => 34,
                'short_description' => 'A sacred geometrical pyramid crafted from Aurvi Plus. Channels cosmic energy for meditation, healing, and Vastu correction.',
                'description' => 'A sacred pyramid used for meditation and Vastu alignment, crafted from Aurvi Plus for amplified energy.',
                'primary_image' => 'auri-images/products/PYRAMID_V2.png',
                'gallery_images' => [
                    'auri-images/products/PYRAMID_V2.png',
                ],
                'weight' => '0.5',
                'dimensions' => '12 x 12 x 10',
                'material' => 'Aurvi Plus compound',
                'origin' => 'Palani Hills',
                'tags' => 'pyramid, vastu, meditation',
                'meta_title' => 'Aurvi Plus Pyramid - Auvri Plus',
                'meta_description' => 'Sacred pyramid crafted for meditation and Vastu correction.',
            ],
        ];

        foreach ($products as $product) {
            Product::updateOrCreate(
                ['slug' => $product['slug']],
                $product
            );
        }
    }
}
